upstream iot_tracker_api {
  server 127.0.0.1:3010;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name iotup.digitalpalm.ai iotdown.digitalpalm.ai;

  client_max_body_size 16k;

  ssl_certificate /etc/letsencrypt/live/iotup.digitalpalm.ai/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/iotup.digitalpalm.ai/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  location / {
    proxy_pass http://iot_tracker_api;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_read_timeout 120s;
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name iotup.digitalpalm.ai iotdown.digitalpalm.ai;
  return 301 https://$host$request_uri;
}
